// native_world.cpp — Spyro's world renderer (0x800258F0 RenderWorldChunks), owned natively.
//
// WHY THIS FUNCTION, AND WHY OWNERSHIP. Widescreen and 60fps both need per-primitive DEPTH for
// 2D-vs-3D discrimination (re-frontier render.own-geometry-family): the framework's 2D widen shifts
// the whole frame a second time at this port's ~2.5% depth coverage (C143) and the uncovered-margin
// strip (issue 0039) is in the same class. Depth (SZ3) is a GTE/scratchpad intermediate ONLY in
// this renderer — never written into the emitted GPU packets (C201; C215 corrects C198's final-arm
// label) — so an interpreted body cannot
// supply it; only an OWNED body can emit depth as it projects.
//
// THE SHAPE, from the corrected structural map (C215) and the recompiled body (generated/shard_3.c
// gen_func_800258F0, ~5000 instructions across 0x800258F0..0x8002A6F4):
//   Phase 1 (0x800258F0..0x800261A0): save callee-saved regs to the fixed save area kSaveArea (no
//     stack frame), load the camera view matrix into the GTE (translation nulled), then walk the
//     environment chunk list (occlusion-group table kEnvironment+8 when a0>=0, flat count-list
//     kEnvironment+0/4 when a0<0), culling each chunk by view frustum + distance (MVMVA against the
//     view matrix, radius shift thresholds vs m_LodDistance) and applying the per-chunk environment
//     geometry/colour animation (INTPL/DPCS blocks writing into chunk vertex/colour arrays).
//     Survivors are written to the work list at kWorkList+0x1C00.
//   Phase 2 (0x800261A0..0x8002A0B0): project every surviving chunk's vertices (RTPS), write
//     SXY2+SZ3 into scratchpad caches, and emit LQ direct plus HQ direct/medium/near gouraud faces
//     with NCLIP, depth/LOD, whole-face clip rejection, fog, texture-table selection, edge fillers,
//     and OT binning. This is where native DEPTH is emitted.
//   Phase 3 (0x8002A0A0..0x8002A6B0): breadth-first adaptive subdivision of oversized near GT3/GT4
//     packets. D_8006D5E4/D_8006D5C8 are child-descriptor tables; each final child chain replaces
//     its parent in the same OT slot. This is not a special-surface renderer (C215 supersedes
//     C198).
//   Epilogue: publish the pool pointer to kPoolPtr, link g_WorldOT, restore registers, return.
//
// HOW THE BODY IS PRODUCED — AND WHY IT IS NOT HAND-TRANSCRIBED. native_terrain.cpp's body
// (0x8004EBA8) was transcribed by hand and it worked: that function is small enough to hold in one
// head, and it verified byte-exact over 400 calls. This one is ~5000 instructions, and hand
// transcription was tried here and MEASURED to fail: the first 40 instructions of the attempt
// carried four defects — a delay-slot load (`s2 = m_SectorPointer`) made conditional when the
// hardware executes it on both paths, an unconditional `s5` increment written as conditional, a
// register substituted (v0 for at), and every `rec_irq_poll` dropped. None of those is visible
// until all 5000 are typed, because the differential can only run a whole body. The instrument was
// wrong for the size, not the person using it.
//
// So world_body.inc is GENERATED by tools/transcribe.py, which renders the recompiled body through
// a BIJECTION — register numbers to MIPS names, lui/addiu address pairs to one named constant,
// offsets to signed form — and nothing else. `transcribe.py check` re-derives the generated source
// from the emitted file and fails on any divergence; it runs in the gate, so the body stays exact
// as the substrate is regenerated. That is a stronger guarantee than a hand transcription can give,
// because it holds by construction rather than by review, and it is what makes the depth hooks
// safe to add: a hook is an annotation keyed to a guest address (world_annotations.json), injected
// at emit time and stripped before the check compares, with its count printed so an annotation can
// never silently mask a divergence.
//
// BYTE-EXACT IS THE ADMISSION REQUIREMENT, not a stretch goal. ndiff snapshots RAM, the scratchpad,
// every GPR and the COP2 register file, runs this body, rewinds, runs the recompiled body, and
// compares. An identity probe proved the differential CAN validate a function of this shape (C202,
// 20/20 exact) and the depth oracle measured the ground's real SZ3 range + per-face OT bins (C201).
#include "cfg.h"
#include "core.h"
#include "game.h"
#include "native_diff.h"
#include "rec_decls.h"
#include "recomp_iface.h"
#include "spyro_game.h"
#include "world_scene_builder.h"
#include "world_scene_capture.h"
#include <cstdlib>
#include <lucent/log.h>

namespace {

// ── Guest globals this renderer reads and writes (C206 / whatis), named rather than raw. These are
//    the SAME names tools/transcribe.py folds the address-materialisation pairs into, so the two
//    halves cannot drift: game/core/guest_names.json is the single table both sides read.
constexpr uint32_t kSaveArea = 0x80077DD8u;    // fixed register-save block (no stack frame)
constexpr uint32_t kCamera = 0x80076DD0u;      // g_Camera: view matrix +0x14, position +0x28
constexpr uint32_t kEnvironment = 0x800785A8u; // g_Environment — the INPUT DATA MODEL, see below
constexpr uint32_t kWorkList = 0x8006FCF4u;    // +0x1C00 survivor chunk list, +0x2000 area end
constexpr uint32_t kPoolPtr = 0x800757B0u;     // packet-pool write pointer (the guest's m_PolyBuf)
constexpr uint32_t kOtBase = 0x80075820u; // g_WorldOT — the WORLD ordering table, not the HUD one
constexpr uint32_t kCullScratch = 0x800771C8u;           // per-chunk cull scratch, zeroed on entry
constexpr uint32_t kSkipLowPolyWorld = 0x8007591Cu;      // g_SkipLowPolyWorld — the LOD kill switch
constexpr uint32_t kEnvironmentAnimations = 0x80078560u; // g_EnvironmentAnimations (0x48 bytes)

// ── g_Environment: WHAT THIS RENDERER READS, and why each offset is EVIDENCE and not a label ─────
// The field names come from the vendored decomp's `Environment` struct (external/spyro-1/include/
// environment.h), which is a REFERENCE — so every one of them is checked against what the body
// above actually does with the offset before it is written down here. Six offsets are used, and
// each check is reproducible from world_body.inc:
//
//   +0x00  m_SectorPointer   — the sector array base. BOTH entry arms load it (world_body.inc:59
//                              `s2 = c->mem_r32(at)`), then index it differently. That is C199's
//                              two entry shapes, arriving independently at the same split.
//   +0x04  m_SectorCount     — the a0<0 arm only: `at = mem_r32(at+4); at <<= 2; s3 = s2 + at`,
//                              i.e. sectors + count*4 = the END pointer of a LENGTH-COUNTED list.
//   +0x08  m_OcclusionGroups — the a0>=0 arm only: `v0 = mem_r32(at+8) + (a0<<2)`, then bytes are
//                              read with mem_r8 and the walk stops on 0xFF. A per-group array of
//                              pointers to 0xFF-TERMINATED sector-index lists — again C199's shape.
//   +0x18  m_LQTexturePointer— Phase 2's texture base (world_body.inc:944).
//   +0x1C  m_HQTexturePointer— HQ medium/near texture-record base (world_body.inc:1878). The LQ/HQ
//                              split is what g_SkipLowPolyWorld selects between.
//   +0x24  m_LodDistance     — read three times and shifted (>>4 at entry, >>7 in Phase 2).
//   +0x28  m_CullingDistance — Phase 1's cull radius, >>7. The CALLER sets it: the environment
//                              layer 0x8002B9CC writes 0x28000 / 0x1C000 / 0x14000 into it and
//                              picks the occlusion group before making this call.
//
// The struct is 0x30 bytes (0x800785A8..0x800785D8), so the three fields this renderer does NOT
// touch — m_SurfaceData/+0x10, m_SurfaceCount/+0x14, m_TextureCount/+0x20, m_TerrainCollision/+0x2C
// — are named for completeness and are NOT evidence from this body.

// Silence "unused" for the names the current body happens not to reference by constant yet; they
// are the map of this renderer's state and are cited by the phase comments above.
[[maybe_unused]] constexpr uint32_t kUnusedGuard[] = {
    kOtBase, kSkipLowPolyWorld, kEnvironmentAnimations};

} // namespace

// The native body. GENERATED — see the note above; edit tools/transcribe.py or the annotations,
// never world_body.inc, and never this body by hand.
void world_native(Core *c) {
  // Register aliases: the MIPS GPRs the body uses, so the transcription reads as the assembly.
  // Every GPR is bound, because ndiff compares all 31 and the body's fixed save area touches them.
  uint32_t &at = c->r[1], &v0 = c->r[2], &v1 = c->r[3], &a0 = c->r[4];
  uint32_t &a1 = c->r[5], &a2 = c->r[6], &a3 = c->r[7];
  uint32_t &t0 = c->r[8], &t1 = c->r[9], &t2 = c->r[10], &t3 = c->r[11];
  uint32_t &t4 = c->r[12], &t5 = c->r[13], &t6 = c->r[14], &t7 = c->r[15];
  uint32_t &s0 = c->r[16], &s1 = c->r[17], &s2 = c->r[18], &s3 = c->r[19];
  uint32_t &s4 = c->r[20], &s5 = c->r[21], &s6 = c->r[22], &s7 = c->r[23];
  uint32_t &t8 = c->r[24], &t9 = c->r[25];
  uint32_t &gp = c->r[28], &sp = c->r[29], &fp = c->r[30], &ra = c->r[31];
  // $zero reads as 0 and is never written; making it const means a generated write to it would be
  // a COMPILE error rather than a silent corruption.
  const uint32_t zero = 0u;

#include "world_body.inc"
}

// ── DID THE BODY ACTUALLY RUN? The counter, and why it is unconditional. ───────────────────────
// This override was installed and logged as installed for a whole session while executing ZERO
// times, because wide_clip.cpp claims the same single slot and registers later (issue 0066). What
// made that invisible is that every downstream signal a run produces — a clean exit, a correct
// picture, an identical screenshot — is exactly what a NON-installed override also produces, since
// the guest body then draws the same frame. So "the picture is unchanged" is evidence of nothing
// until the body is known to have run, and a screenshot compare without this counter is a
// measurement of the guest renderer against itself.
//
// Hence a counter that is always on (an increment, not a diagnostic) and a run-end line that prints
// even when it is ZERO — a silent report here would be indistinguishable from "I never looked".
namespace {
long s_world_calls = 0;
long s_world_flat = 0;
long s_world_occ = 0;
} // namespace

void spyro_world_native_finish() {
  if (!cfg_on("PSXPORT_NATIVE_WORLD")) {
    lucent::info("worldnative",
                 "PSXPORT_NATIVE_WORLD was OFF: the guest body drew every world frame in this run. "
                 "Nothing in this run says anything about the native body.");
    return;
  }
  if (s_world_calls == 0) {
    lucent::error("worldnative",
                  "PSXPORT_NATIVE_WORLD=1 but the native world body ran ZERO times. It was "
                  "registered and then never called — either this run never reached the field, or "
                  "something registered later took the single override slot at 0x800258F0 (issue "
                  "0066). Any picture or gate result from this run is about the GUEST body.");
    return;
  }
  lucent::info("worldnative",
               "the native world body RAN {} time(s) this run: {} flat-list (a0<0) + {} "
               "occlusion-group (a0>=0). This is what makes a picture from this run evidence "
               "about the native body rather than about the guest one.",
               s_world_calls,
               s_world_flat,
               s_world_occ);
}

// The owned override: dispatch the native body, and under ndiff verify it against the recompiled
// body. Registration is below, behind an explicit flag.
//
// THE TWO LIST SHAPES ARE SEPARATE ndiff SITES, deliberately. C199 measured that this renderer is
// entered two structurally different ways — a0<0 walks the length-counted flat sector list (from
// the render driver 0x8001EA6C), a0>=0 walks a 0xFF-terminated byte-indexed occlusion-group list
// (from CreateEnvironment 0x8002B9CC) — and they share almost nothing after the prologue. A single
// site would report one call count that could be entirely one shape, so "N calls verified" would
// read as coverage it does not have. Two sites make the log state which shapes actually ran, and
// give each its own budget so a flood of one cannot starve the other.
void world_owned(Core *c) {
  const int32_t selection = (int32_t)c->r[4];
  const bool flat = (int32_t)c->r[4] < 0;
  s_world_calls++;
  if (flat) {
    s_world_flat++;
  } else {
    s_world_occ++;
  }
  spyro::world_scene_capture::begin(c);
  ndiff_run(
      c, flat ? "world-flat@0x800258F0" : "world-occ@0x800258F0", world_native, gen_func_800258F0);
  if (cfg_on("PSXPORT_WORLD_SCENE_ORACLE")) {
    spyro::world_hq_recipe::Audit audit;
    const auto recipe = spyro::world_scene::build(c, selection, &audit);
    if (recipe.status != spyro::world_recipe::Status::Ready &&
        recipe.status != spyro::world_recipe::Status::ValidEmpty) {
      lucent::error("worldsceneoracle",
                    "semantic builder refused status={} reason={}",
                    (uint32_t)recipe.status,
                    recipe.refusal);
      abort();
    }
    if (spyro::world_scene_capture::verify(c, recipe.faces, audit) !=
        spyro::world_scene_capture::Status::Match) {
      abort();
    }
  }
}

void spyro_register_native_world() {
  // OFF by default. The body is byte-exact by construction (transcribe.py's round-trip check runs
  // in the gate), but "byte-exact source" is not the same claim as "byte-exact EXECUTION": the
  // differential has not yet been run over this function on real frames. Until it has, installing
  // this would put an unverified 5000-instruction body on the shipping picture path.
  //
  // Turn it on with PSXPORT_NATIVE_WORLD=1 to run the differential (PSXPORT_NDIFF=<n>).
  if (!cfg_on("PSXPORT_NATIVE_WORLD")) {
    return;
  }
  lucent::info(
      "native",
      "PSXPORT_NATIVE_WORLD=1 — the native world body OWNS 0x800258F0 (RenderWorldChunks). "
      "It is a generated transcription of the recompiled body; run with PSXPORT_NDIFF to "
      "verify execution, and treat a run without NDIFF as UNVERIFIED.");
  psxport_recomp()->shard_set_override(0x800258F0u, world_owned);
}
