// spyro_game.h — declarations for Spyro's cohesive game-side subsystems.
#include <cstdint>
//
// The framework never includes this; Spyro1Runtime composes these operations.
#pragma once

class Game;
class Core;

void spyro_install_recomp(); // game/core/recomp_register.cpp — installs the generated substrate

// game/core/vsync.cpp — callback registration + host clock for the title-owned field scheduler.
void spyro_register_field_scheduler();

// game/core/cd_queue.cpp — observes (and will own) the CD request queue service routine.
void spyro_register_cd_queue();

// True only while the guest's boot/logo/loading sequence at 0x800127C0 is executing.  The
// observer in vsync.cpp uses this lifetime rather than guessing boot from a frame number.
bool spyro_boot_sequence_active();

// The first guest function this port OWNS outright (native_rand.cpp) — the recompiled body never
// runs once installed. Verified per call against that body under PSXPORT_NDIFF.
void spyro_register_native_rand();

// Hot leaf functions owned outright (native_leaf.cpp), chosen with tools/own_candidates.py.
void spyro_register_native_leaves();

// 3-word vector add/sub and the libgte angle-table interpolator (native_vec.cpp).
void spyro_register_native_vec();

// Geometry leaves that use the GTE (native_gte.cpp) — scalar logic native, COP2 via the platform
// model.
void spyro_register_native_gte();

// native_angle.cpp — the engine's 8-bit/12-bit angle helpers and its calibrated spin loop.
void spyro_register_native_angle();

// native_util.cpp — strlen, two set-and-return-previous globals, 2D distance, display-list link.
void spyro_register_native_util();

// native_printf.cpp — PsyQ printf's non-leaf argument-homing wrapper. The formatter remains a
// separate dispatch target, so the generated wrapper stays available as the per-call oracle.
void spyro_register_native_printf();

// native_actor_mesh_scratch.cpp — owns InitActorMeshScratchRegions 0x8005B6F8. Its only child,
// FillWord, is already owned; the retained generated parent is its per-call oracle.
void spyro_register_native_actor_mesh_scratch();

// native_spu_pio_upload.cpp — owns PsyQ WriteSpuRamPio 0x8005BE88. Its spin and printf children
// are already owned; the retained generated parent is its per-call oracle.
void spyro_register_native_spu_pio_upload();

// native_spu_hardware_init.cpp — owns PsyQ InitSpuHardware 0x8005BBF4. Its spin, printf, and PIO
// upload children are already owned; the retained generated parent is its per-call oracle.
void spyro_register_native_spu_hardware_init();

// native_text_sprites.cpp — owns BuildTextSprites 0x800181AC. Its FillWord and CopyVector children
// are already owned; the retained generated parent is its per-call oracle.
void spyro_register_native_text_sprites();

// native_memcard_event_stack.cpp — owns libmcrd's 0x80068F44 event-stack push. Its printf child
// is already owned; the retained generated parent is its per-call oracle.
void spyro_register_native_memcard_event_stack();

// native_memcard_operations.cpp — owns the reached libmcrd request starters 0x8006635C and
// 0x800665B8; both retain their generated bodies as NDIFF oracles.
void spyro_register_native_memcard_operations();
// native_terrain.cpp — BRING-UP, installs nothing unless PSXPORT_NATIVE_TERRAIN=1: a full native
// body for the terrain renderer 0x8004EBA8, under per-call differential verification (issue 0037).
void spyro_register_native_terrain();
int spyro_native_terrain_selftest();
bool spyro_terrain_submit(Core *, int32_t selector, uint32_t matrix1, uint32_t matrix2);
void spyro_register_actor_chain_oracle();

// native_world.cpp — BRING-UP, installs nothing unless PSXPORT_NATIVE_WORLD=1: a full native body
// for the world renderer 0x800258F0 (RenderWorldChunks), the depth/widescreen gate. The body is
// GENERATED by tools/transcribe.py from the recompiled one (game/core/world_body.inc) and is
// byte-exact by construction; execution is verified per call by PSXPORT_NDIFF.
void spyro_register_native_world();
// Run-end denominator for the native world body: how many times it ACTUALLY ran, printed even when
// that is zero. See the note in native_world.cpp — an unchanged picture is not evidence the body
// ran.
void spyro_world_native_finish();
int spyro_actor_chain_oracle_selftest();

// native_render.cpp — MEASUREMENT, installs nothing unless PSXPORT_NDIFF_IDENTITY=<addr,…>: can the
// per-call differential validate a geometry renderer at all? (re-frontier
// render.own-geometry-family)
void spyro_register_native_render();
// Emits the run-end denominator for native_render.cpp's optional sprite-queue input census.
void spyro_sprite_queue_census_finish();
// …and for the RenderWorldChunks 0x800258F0 input census (the frontier step after C198).
void spyro_world_census_finish(Core *c);

// world_animation_oracle.cpp — PSXPORT_WORLD_ANIMATION_ORACLE=1 checks the native phase-1 world
// animation against the retained body by requiring identical guest RAM after both legs.
void spyro_world_animation_oracle_install();
void spyro_world_animation_oracle_snapshot(Core *c);
void spyro_world_animation_oracle_finish();

// wide_clip.cpp — widescreen by moving the guest's own clip-bound immediates in guest RAM and
// running the five contributing renderers interpreted (11 sites). Inert at 4:3.
void spyro_register_wide_clip();
