#!/usr/bin/env python3
"""Generate the C++ executable catalog from the authoritative title manifests."""

from __future__ import annotations

import argparse
import pathlib

import title_identity

ROOT = pathlib.Path(__file__).resolve().parent.parent
TITLE_ENUMS = (
    ("spyro1", "Spyro1"),
    ("spyro2", "Spyro2"),
    ("spyro3", "Spyro3"),
)


def _cpp_string(value: object) -> str:
    if not isinstance(value, str):
        raise title_identity.Refused(f"catalog string field has non-string value {value!r}")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render(*, root: pathlib.Path = ROOT) -> str:
    """Return one constexpr catalog; executable.json remains the only facts authority."""
    entries: list[str] = []
    for slug, enum_name in TITLE_ENUMS:
        manifest = title_identity.load_manifest(slug, root=root)
        facts = title_identity.expected(manifest)
        entries.append(
            "\n".join(
                (
                    "    ExecutableIdentity{",
                    f"        .title = SpyroTitle::{enum_name},",
                    f"        .displayName = {_cpp_string(manifest['title'])},",
                    f"        .serial = {_cpp_string(manifest['serial'])},",
                    f"        .fileSize = {facts['size']}u,",
                    f"        .sha256 = {_cpp_string(facts['sha256'])},",
                    f"        .entry = 0x{facts['entry']:08X}u,",
                    f"        .globalPointer = 0x{facts['gp']:08X}u,",
                    f"        .textAddress = 0x{facts['text_address']:08X}u,",
                    f"        .textSize = 0x{facts['text_size']:08X}u,",
                    f"        .stackAddress = 0x{facts['stack_address']:08X}u,",
                    f"        .stackOffset = 0x{facts['stack_offset']:08X}u,",
                    "    },",
                )
            )
        )
    return "\n".join(
        (
            "// Generated by tools/generate_title_catalog.py from titles/*/executable.json.",
            "// Do not edit: change the measured manifest and rebuild.",
            "#pragma once",
            "",
            '#include "spyro_runtime.h"',
            "",
            "#include <array>",
            "",
            "namespace spyro::generated {",
            "",
            "inline constexpr std::array<ExecutableIdentity, 3> kExecutableCatalog{{",
            *entries,
            "}};",
            "",
            "} // namespace spyro::generated",
            "",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    try:
        text = render()
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
    except (OSError, title_identity.Refused) as error:
        parser.exit(2, f"REFUSED: {error}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
